### ISSUE TITLE
TN5250 System Error

### ISSUE THREAD

**Issue by ArtKrieger** [tn5250/tn5250#11]
When launching the TN5250 emulator, the main window opens but when I attempt to connect, the program crashes and I receive a System Error - "Exception Processing Message 0xc0000005 - Unexpected parameters". I believe this may be a Windows 11 issue as I copied a Netmanag.32 folder from a working PC to this one and received the same error. Has anyone encountered this and how can it be fixed?
![image](https://github.com/user-attachments/assets/f751a1a2-e7cf-4d18-ba71-105c004ee0df)

**Comment by kadler** [comment]
I don't know what Netmanag.32 is. Did you build tn5250 yourself or get it from somewhere?

**Comment by kadler** [comment]
What emulation?

**Comment by kadler** [comment]
That doesn't look like any tn5250 version I've ever seen. I think you have a different thing, which calls itself tn5250. I know at least Mochasoft calls their emulator "tn5250" as well, probably others too. I think you need to figure out who provides yours and open an issue with them, but it's not this project. Good luck!

**Comment by kadler** [comment]
May be NetManage RUMBA. Looks like they got bought out by MicroFocus and now owned by Rocket: https://www.rocketsoftware.com/products/host-connectivity/rumba
