### ISSUE TITLE
Cursor in protected area of display

### ISSUE THREAD

**Issue by ghost** [tn5250/tn5250#6]
Hello, 

I have some trouble with the tn5250 emulator (on IBM i) in VSCODE.

When i press back space on the first screen the cursor is locked and i can't unlock it with the "CTRL" key.

Do you know how to solve the problem please ? 

![image](https://github.com/tn5250/tn5250/assets/150674819/7f1e2313-9c02-44de-b0e5-6c1ea0a505d7)
![2023-11-21 18_00_28-Window](https://github.com/tn5250/tn5250/assets/150674819/cadb0cd0-5c03-4ec7-b487-e4661ad3ff06)

Thank you !

**Comment by kadler** [comment]
The standard keyboard shortcut for this is Ctrl-r to reset the cursor.

FYI this and others are others documented in the man page. It starts here, though it's not easy to read the unformatted source: https://github.com/tn5250/tn5250/blob/main/doc/tn5250.1#L59
